name: backend-checks

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  checks:
    uses: giyomoon/workflows/.github/workflows/rust-checks.yml@main
    with:
      rust-version: nightly
